name: Web App

on:
  pull_request:
    branches:
      - alpha
      - feature/*
    paths:
      - web-app/**
      - .github/workflows/web-app.yml

jobs:
  test:
    defaults:
      run:
        working-directory: web-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test -- --no-watch --code-coverage
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          working-directory: web-app
          wait-on: 'http://localhost:4200'
      - uses: actions/upload-artifact@v2
        with:
          name: cypress video artifacts
          path: web-app/cypress/videos
      - uses: actions/upload-artifact@v2
        with:
          name: cypress screenshot artifacts
          path: web-app/cypress/screenshots
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: web-app/dist/web-app
  deploy:
    needs: ['test', 'build']
    defaults:
      run:
        working-directory: 'web-app-cdk'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - run: npm run cdk -- synth
