name: Web App Destroy

on:
  pull_request:
    branches:
      - alpha
      - feature/*
    types: [closed]
    paths:
      - web-app/**
      - .github/workflows/web-app.yml

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app-cdk
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm install
      - run: yes | npm run cdk -- destroy -c stackName=WebApp-${BRANCH//\//-} -c bucketName=${BRANCH//\//-} -c sourcePath=$(pwd)/../build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          BRANCH: ${{ github.base_ref }}
