name: Web App

on:
  pull_request:
    branches:
      - alpha
    paths:
      # - 'web-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install
        working-directory: web-app
      - run: npm run test -- --watch false
        working-directory: web-app
