name: Web App CDK

on:
  pull_request:
    branches:
      - alpha
      - feature/*
    # paths:
      # - 'web-app-cdk/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install
        working-directory: web-app
      - run: npm test -- --no-watch --code-coverage
        working-directory: web-app
